name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Package Application
      run: zip -r app.zip .

    - name: Transfer Files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        source: "./app.zip"
        target: "~/node-app"
        timeout: 120s
        strip_components: 0 

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          cd ~/node-app
          unzip -o app.zip
          npm install
          pm2 stop all || true
          pm2 start index.js --name "node-app"
